### ISSUE TITLE
Get/ Set Inputs in the CLI

### ISSUE THREAD

**Issue by orferch** [StuPro-TOSCAna/TOSCAna#101]
To get or set Inputs in the CLI there is a need for a new Option and Parameter(s).

For get it could for example look like this:

`toscana transformation input -c csar -p platform` which prints all needed Input <key, value> pairs

To set inputs it could look like this:

`toscana transformation input -c csar -p platform -i key value` or
`toscana transformation input -c csar -p platform -i <key,value>` or
`toscana transformation input -c csar -p platform -ik key -iv value`

Another possibility would be to creat a new command input with subcommands:

to get needed inputs:

`toscana input get -c csar -p platform`

to set the inputs:
`toscana input set -c csar -p platform -i key value` or
`toscana input set -c csar -p platform -i <key,value>` or
`toscana input set -c csar -p platform -ik key -iv value`

Let me know which you prefer, or if you have a better idea please suggest it!

**Comment by hnicke** [comment]
I would use:
`toscana input -c csar -p platform key1=value1 key2=value2 key3=value3`
for manual input and
`toscana input -c csar -p platform -f path/to/properties/file`
Whereas the properties file should have this format:
```
KEY=VALUE
KEY2=VALUE2
...
```
This format is both propper bash syntax and proper java properties syntax.

**Comment by hnicke** [comment]
btw: what about a shortcut for transformations?
`-c csar -p plattform` -> `-t csar/platform`
An alias to `toscana input -c csar -p platform` could be `toscana input -t csar/platform` (slash is not allowed in an identifier)

**Comment by orferch** [comment]
yeah thought about a shortcut for transformations, your suggestions are great!

**Comment by hnicke** [comment]
Maybe we should ditch the -t, -c and -p flag -- specification of the transformarion is not optional and should not be expressed with an option. Instead, always use the short notation without -t:
`toscana input csar/platform ...`
Maybe this design could be applied to other commands, too

**Comment by orferch** [comment]
I don't really know, it was `toscana input csar platform` before and the customer didn't like it.
With the -c and -p flags you at least know what is wanted, the solutions with csar/platform could be critized because slash is not allowed...
