### ISSUE TITLE
Add RequestMapping to start a transformation

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#110]
Currently it is not possible to start a transformation with the api, therefore we have to add a API call `GET /csars/{csar}/transformations/{platform}/start` to start the transformation

**Comment by hnicke** [comment]
As far as I understood this would not be conform with REST, because start is not a resource. I'd use a `POST` with parameter `action=start`. We could also abort the transformation that way.

**Comment by c-mueller** [comment]
Aborting is not possible (at least not really) if the plugins dont handle it correctly, thats why i would not even implement a Mapping for that yet. Canging the Mapping from `GET` to `POST` should be good enough!

**Comment by hnicke** [comment]
I think you didn't quite get my point yet. I meant: I'd use a `POST /api/csars/{csar}/transformations/{platform}?action=start`

**Comment by hnicke** [comment]
https://stackoverflow.com/questions/2447722/rest-services-exposing-non-data-actions
