### ISSUE TITLE
Change folder structure

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#124]
The folder structure needs to be updated because the core package contains the real core but also the REST API. To ease communication an provide a better structure we decided to rename the core folder in the repository root to server and move the api package one level up.

`core` -> `server`
`/server/src/main/java/org/opentosca/toscana/core/api/` -> `/server/src/main/java/org/opentosca/toscana/api/`

**Comment by c-mueller** [comment]
I will handle this once all features regarding the api are implemented (especially the open ones)
