### ISSUE TITLE
Experimental branch

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#13]
@hnicke had the idea to greate a branch with a unstable version of our program that get deployed on every commit into an live environment to make tests a lot easier.

Another advantage may be that others at any time have the possible to test our program without having to deploy if for themselves. 

What is the opinion of the rest of the team?

**Comment by mmunozba** [comment]
I don't see many (if any) downsides to this so I'd support this suggestion.

**Comment by hnicke** [comment]
discussion moved to #89
