### ISSUE TITLE
Remove hardcoded server ip and port in the CLI

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#155]
Currently the CLI uses a hardcoded port and IP. To enable configuration I would suggest to create a properties file in the home dir of the user. This would give a adress like this: `<user-home-dir>/.toscana/cli.properties`. 

To configure the CLI without editing files I would recommend using a subcommand named `config`.

Set the ip and port:
```
toscana config ip "192.168.0.1"
toscana config port "5000"
```
View the settings:
```
toscana config ip 
> 192.168.0.1
```
```
toscana config port 
> 5000
```

In the properties file the values are saved like this:
```
ip=192.168.0.1
port=5000
```
with this notation the file is bash compatible.

**Comment by c-mueller** [comment]
We should keep it together and maybe call it cli endpoint with the value (for example) `http://localhost:8080` this also allows support of HTTPS based instances.

Thi also allows you to set the endpoint to something like `http://192.168.99.100:8080/toscana`you might have a adress like this when running on tomcat

**Comment by hnicke** [comment]
- setting the endpoint via `CLI` is unnecessary
- Instead, i propose following:
  - On `CLI` startup, `CLI` reads endpoint from a config file.
  - Documentation (e.g. man page) must provide information where this file is located
    - proper location for linux: $HOME/.config/toscana/
    - proper location for windows: $HOME/AppData/toscana/ (?)
- sensible default value should be `http://localhost:{port}`, whereas {port} should NOT be `8080`. I propose something like `8083`

We need this external configuration file because resources located in the jar are immutable at runtime.

**Comment by nfode** [comment]
As I mentionend in the PR I do not think setting the url int the CLI is unneccessary, for Example if I had to use our CLI on Windows I do not have any idea how to edit the `.properties` file without extra research.
@hnicke for you as unix user it might seem easy to use `vim ~/.config/toscana/cli.properties` ;)

**Comment by hnicke** [comment]
@nfode Navigate to file with explorer -> right click -> open with -> notepad?

**Comment by nfode** [comment]
@hnicke I think AppData is a hidden folder, so I have to click to about 5 submenus to see the hidden folder...

**Comment by nfode** [comment]
But hopefully I never have to use it on Windows 🤣

**Comment by hnicke** [comment]
A developer should know how to access hidden files. Implement a cli command to set the endpoint if you like -- but we really have other problems than that.
