### ISSUE TITLE
Move to "feature driven" development in the CLI

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#156]
As I already suggested in the CLI PR, I think it would be a good idea to Merge the CLI Branch into master (after fixing most of the codacy issues). After that develpoment should continue in a "feature driven" manner, just like we do in the core. This will make reviewing way easier.

**Comment by nfode** [comment]
@c-mueller you reviewed the CLI so if you say this is the best way I think it is ok. 
Also if we merge the CLI we can fix some issues like #124 (change the folder names).
