### ISSUE TITLE
Design a CLI

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#16]
TODO:
- [x] Design the CLI
- [x] Design the architecture

**Comment by JensMueller2709** [comment]
#22

**Comment by koppor** [comment]
Please document the chosen CLI solution using an archictural decision: https://github.com/eclipse/winery/blob/master/docs/adr/template.md

Currently preferred solution: Apache Commons CLI: https://commons.apache.org/proper/commons-cli/

**Comment by JensMueller2709** [comment]
i updated the documents and also added the architectural decision with the given form from .
also i added some possible commands of the CLI which can be found in the [requirements doc](https://github.com/StuPro-TOSCAna/TOSCAna/blob/cli-architecture/requirementsCli.md). I think it is a good base for further discussions.

**Comment by nfode** [comment]
@orferch it might be better to create a architectural draft before implementing it.

**Comment by koppor** [comment]
@JensMueller2709 The link to the requirements doc needs and update. - I updated above the link to the ADR template.

**Comment by nfode** [comment]
Recommendations by @miwurster:
- https://github.com/remkop/picocli
- https://github.com/cbeust/jcommander
