### ISSUE TITLE
Check out how the HTML files for the target artifact can be created

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#162]
We decided to use HTML for creating a documentation for every target artifact. 
This process might be easier using a template engine.

Spring allready has **Thymeleaf**. 

Now we need to take a look at how do we integrate the process creating HTML docs into our transformation process. @c-mueller already had the idea to create a `DocumentBuilder`.

**Comment by c-mueller** [comment]
Has been implemented using a simpler form (see `ReadmeBuilder`)
