### ISSUE TITLE
Fix Jenkins

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#172]
The Jenkins builds currently fail due to several errors

The logiles from my jenkins instance can be found at the link below:
[10.133.7.44-Jenkins-log.txt](https://github.com/StuPro-TOSCAna/TOSCAna/files/1462196/10.133.7.44-Jenkins-log.2.txt)

**Comment by nfode** [comment]
It seems like it has to do with the CLI.

**Comment by c-mueller** [comment]
Because we are running a Good jenkins installation now, this seems to be fixed
