### ISSUE TITLE
Use retrofit-wrapper to interact with the api in the cli

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#188]
Instead of using a seperate implementation of the Retrofit Service the CLI should use the `retrofit-wrapper` module.

This will also make testing of the cli way easier, because the proivded `TOSCAnaAPI` class is really easy to mock

**Comment by orferch** [comment]
Left TODO:
- [ ] Nullpointer gets thrown with empty lists and other stuff 
- [ ] Tests

**Comment by nfode** [comment]
Where is the PR?

**Comment by orferch** [comment]
will open it today
