### ISSUE TITLE
Return Error Code 1 if the operation failed

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#189]
Currently the CLI returns code 0 (success) even if the execution failed. This is wrong behaviour it should return code 1 (or at least not 0)

**Comment by hnicke** [comment]
> Commands are expected to return 0 on success, 1 upon a fatal error, and 2 when invoked incorrectly (usage error)

[source](https://blogs.oracle.com/alanc/collected-advice-on-unix-cli-design-implementation)
