### ISSUE TITLE
Basic plugin workflow

### ISSUE THREAD

**Issue by JensMueller2709** [StuPro-TOSCAna/TOSCAna#192]
I thought about a basic plugin workflow. What we get from the core component and what the plugin has to do. Therefore i just draw a simple flow with my first ideas and want to show you to start a discussion about it.

![simple plugin flow - page 1](https://user-images.githubusercontent.com/26904400/32727162-d329a0c6-c87b-11e7-9cce-8aa5a11c680d.png)

I think the image is self explanatory since it is very simple. Neverthess if you have any question, just ask.

**Comment by nfode** [comment]
It is currently the plan that the plugins get a *jgrapht* to work on. No list. What is the job of the OrderManager to just iterate over the List we do not need a extra class. 

But the main thing is that in your basic workflow the whole idea of our transformation lifecycle is missing.

**Comment by hnicke** [comment]
In the last sprint meeting (for sprint 3) @koppor wanted us to stick closer to (propperly modeled) UML when drawing diagrams. You use uml class diagram to describe a workflow here, which is incorrect AFAIK.

In our currently established domain language, the TargetArtifact contains the readme and deployment.sh. (please verify, @nfode ).

I think the plugins can't simply look at the nodetype of a node and read it's attributes. What about unfulfilled requirements of a node? They are meant to be fulfilled by the orchestrator/plugin. This is the reason I'm currently taking much care in designing all the normative capabilities.

**Comment by nfode** [comment]
The is not necessarily called `deployment.sh` but it is definitively include in the target artifact.
