### ISSUE TITLE
Create ADR for Plugin Mappings

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/TOSCAna#195]
Our mappings for TOSCA models and their respective counterparts on the target platforms should be put in writing through ADR. This especially includes changes to model structure or elements made in order to allow the transformation for the target platforms.

e.g. containerization for Kubernetes, incompatible elements etc.

**Comment by c-mueller** [comment]
I think a ADR is not enough for this task, every plugin should handle this in their documentation. Therefore this issue is closed!
