### ISSUE TITLE
Build cloudformation plugin support for LAMP-stack

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/TOSCAna#197]
Since the transformation of a docker app seemed unfit as a first transformation, a basic plugin that can transform a LAMP stack for AWS CloudFormation should be implemented as suggested.

**Comment by JensMueller2709** [comment]
for this we need a LAMP stack CSAR i think. The CloudFoundry-Plugin-Team need this as well.

**Comment by mmunozba** [comment]
Moved to #208.

**Comment by nfode** [comment]
This issue has nothing to do with the CSAR? It is in general about building a plugin that can handle a LAMP stack. Or am I wrong?

**Comment by mmunozba** [comment]
That was a mistake on my part, #208 was supposed to replace this issue but ended up being the LAMP-stack CSAR creation. This issue can remain open.
