### ISSUE TITLE
Clarify name for AWS CloudFormation plugin

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/TOSCAna#198]
Currently, we use different names or abbreviations for the AWS CloudFormation plugin.
In the project structure, there is a folder `server/src/main/java/org/opentosca/toscana/plugins/awscf` and the plugin contained within is called `CloudFormationPlugin`.

I suggest we change the folder name to `cloudformation` and use it instead of awscf or other abbreviations.

**Comment by mklopp** [comment]
This is true there are several names at the moment. I think renaming the folder to `cloudformation` makes sense. Another possibility would be awscfn and not awscf but as I said `cloudformation` is just fine

**Comment by mklopp** [comment]
This should be solved with merging #229

**Comment by c-mueller** [comment]
Closed because #237 has been merged
