### ISSUE TITLE
 Clarify usage of "k8s" as abbreviation for kubernetes

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#202]
Discussed this a while ago with @hnicke, he stated that "k8s" is a weird abbreviation since no one not related with this topic has no idea. After some time I have the same opinion. 

What do the other think? I suggest to use **kubernetes** not *k8s*.

**Comment by mmunozba** [comment]
I agree. I got confused myself when I first heard the term k8s.

**kubernetes** seems like the better option
