### ISSUE TITLE
Create example LAMP-stack CSAR

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/TOSCAna#208]
Since the transformation of a docker app seemed unfit as a first transformation for CloudFoundry and AWS CloudFormation, we should create an example LAMP-stack CSAR.

**Comment by hnicke** [comment]
I suggest you use the non-normative types for apache and php. What is your plan?

**Comment by mmunozba** [comment]
We are currently attempting to create the yaml with the non-normative types for apache, mysql and dbms.mysql and a server as a normative compute node. We're still figuring out the PHP node. 
The WIP template can be found on the [`resources/lamp-csar`](https://github.com/StuPro-TOSCAna/TOSCAna/tree/resources/lamp-csar) branch.
