### ISSUE TITLE
Build cloudfoundry plugin support for LAMP-stack

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/TOSCAna#209]
Since the transformation of a docker app seemed unfit as a first transformation, a basic plugin that can transform a LAMP stack for Cloud Foundry should be implemented as suggested.

**Comment by JensMueller2709** [comment]
before we could create such a "test"-plugin we have to create a test-LAMP-csar. Afterwards i will start.
At this time maybe we have the chance to use the effictive model or the JGraph.

**Comment by JensMueller2709** [comment]
implemented
