### ISSUE TITLE
Investigate mapping of a TOSCA OS capability to a Docker base image

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#218]
# Map OS to Base Docker image

In my eyes this is the most important part of the Kubernetes plugin to allow the transformation of generic topologies based on Compute nodes.

## So what's the problem?

A Compute node has a Operating System capability. If i undertstood correcty this means that the Compute node is executing the operating system described in the capability.
The following images show parts of the TOSCA Spec describing the "Schema" and a instance of this capability:

#### *Schema*

![image](https://user-images.githubusercontent.com/2706976/32873297-919c3d00-ca8b-11e7-98f4-28913760d304.png)

#### *Instance*
![image](https://user-images.githubusercontent.com/2706976/32873440-656ec742-ca8c-11e7-9d55-c932baab58b8.png)

There is no real definition on how these values have to be popultated. This is extending the fact that the are not even required. 

We now have to create a Mapping between Docker base images (for example `ubuntu:17.10`) and a given OS capability. If the Values are incomplete, we either have to make reasonable assumptions or just prevent the launch of the transformation, by just saying there is no docker base image in our database. Of course the "database" (some sort of text file) will be updatable and customizable. 

## Supported Architectures (By Docker):

Docker provides a set of standart images (called the `Standard Library`) in platform specific organisations (Taken from [`here`](https://github.com/docker-library/official-images/blob/master/README.md)):

-	Architectures officially supported by Docker, Inc. for running Docker: (see [download.docker.com](https://download.docker.com/linux/))
	-	IBM z Systems (`s390x`): https://hub.docker.com/u/s390x/
	-	ARMv7 32-bit (`arm32v7`): https://hub.docker.com/u/arm32v7/
	-	Windows x86-64 (`windows-amd64`): https://hub.docker.com/u/winamd64/ *NOT IMPORTANT* due to the missing 
	-	Linux x86-64 (`amd64`): https://hub.docker.com/u/amd64/ *IMPORTANT*
-	Other architectures built by official images: (but *not* officially supported by Docker, Inc.)
	-	IBM POWER8 (`ppc64le`): https://hub.docker.com/u/ppc64le/
	-	x86/i686 (`i386`): https://hub.docker.com/u/i386/
	-	ARMv8 64-bit (`arm64v8`): https://hub.docker.com/u/arm64v8/
	-	ARMv6 32-bit (`arm32v6`): https://hub.docker.com/u/arm32v6/ (Raspberry Pi 1, Raspberry Pi Zero)
	-	ARMv5 32-bit (`arm32v5`): https://hub.docker.com/u/arm32v5/

**Comment by hnicke** [comment]
As far as I understood our requirements, we should not strive for 100% compatibility for all architectures / os /distros -- although this would be nice, it would be quite overkill. I suggest we focus on `os: linux` and `distro: ubuntu`.
