### ISSUE TITLE
Missing API Calls in Retrofit Wrapper

### ISSUE THREAD

**Issue by orferch** [StuPro-TOSCAna/TOSCAna#230]
The retrofit wrapper currently doesn't contain a `create transformation` call which is necessary to start a transformation later. Also doesn't contain `delete Csar` and `delete Transformation` calls.

The `updateProperties` call requires a `TransformationProperties` Object which contains a List of `TransformationProperty`. This class doesn't contain Setters, which are needed to provide the properties, the user set through the CLI with manual or file input.

**Comment by nfode** [comment]
Why do you not implement it yourself?

**Comment by c-mueller** [comment]
gonna fix that real quick

**Comment by orferch** [comment]
already fixed it myself

**Comment by c-mueller** [comment]
Alright, gonna close this then.
