### ISSUE TITLE
TOSCA spec version

### ISSUE THREAD

**Issue by mklopp** [StuPro-TOSCAna/TOSCAna#238]
I thought we use the [TOSCANA v1.0](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.0/TOSCA-Simple-Profile-YAML-v1.0.html) for our project, but @hnicke is referencing the [TOSCANA v.1.1](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.1/cs01/TOSCA-Simple-Profile-YAML-v1.1-cs01.html) on several occasions. So I wonder which one we should rely on.

**Comment by hnicke** [comment]
I've used TOSCA YAML v1.1-cos01 from 04.10.17.  [link](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.1/cos01/TOSCA-Simple-Profile-YAML-v1.1-cos01.pdf) for the effective model.

**Comment by nfode** [comment]
Since @hnicke used version 1.1 we are working with this version.
