### ISSUE TITLE
YAML File Generator

### ISSUE THREAD

**Issue by JensMueller2709** [StuPro-TOSCAna/TOSCAna#244]
For Cloud Foundry i need in every targetartifact a yaml-file. Whats about the other plugins?
Maybe it make sense to generate a general YAML File Generator.

**Comment by nfode** [comment]
In kubernetes we use the following Java client: [kubernetes-client](https://github.com/fabric8io/kubernetes-client) which can produce yaml files for us. 

Is there something similar to this for CloudFoundry?

**Comment by JensMueller2709** [comment]
I didnt find something similar for CF so far.
(YamlBeans)[https://github.com/EsotericSoftware/yamlbeans] looks interesting for my need.

**Comment by c-mueller** [comment]
For Java Object to JSON/XML/YAML mapping please consider using [Jackson](https://github.com/FasterXML/jackson). The reason why is simple: The core is already using it for serialization (it's included with the Spring Framework).

If you want ot use it you have to construct a ObjectMapper Instance with a YAMLFactory:
```java
ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
try {
    System.out.println(mapper.writeValueAsString(object));
} catch (JsonProcessingException e) 
    e.printStackTrace();
}
```
The second part serializes the object and prints it as yaml.

**Comment by JensMueller2709** [comment]
If we use already a lib in the core, I think it is the best to use this one for the same purpose.

**Comment by c-mueller** [comment]
I consider this as clarified. Will Therefore close the issue.
