### ISSUE TITLE
Winery does not have native support for non-normative types used in the YAML 1.1 specification

### ISSUE THREAD

**Issue by JensMueller2709** [StuPro-TOSCAna/TOSCAna#260]
While testing the LAMP-csar we get an error from the winery:

`2017-11-26T20:58:50,614 [ec-6] INFO  o.o.t.c.parse.CsarParseServiceImpl   - An error occured while parsing csar 'org.opentosca.toscana.core.csar.CsarImpl@75600e32' 
org.eclipse.winery.yaml.common.exception.MultiException: Node Type "{http://www.eclipse.org/winery/ns/simple/yaml/1.1/default}tosca.nodes.WebServer.Apache" is undefined.
null`

We found out that the winery has problems with parsing non-normative types like `WebServer.Apache`or `Database.MySQL`.

As far as i know we use the eclipse winery to parse the csar and we support non-normative types. So this could be an issue for us.

**Comment by mklopp** [comment]
So we need to discuss whether we drop the non-normative types as well for find a workaround

**Comment by koppor** [comment]
Is it that hard to cerate an additional YAML file containing the non-normative types? This can be imported by your YAML files.

After you created that file, @kleinech and me can think of including that in Winery (performance overhead, because the file has to be internally loaded at each parsing run).

**Comment by mklopp** [comment]
I guess that's another option. I'd leave them out.
But that's just my opinion

**Comment by koppor** [comment]
Non-normative types are ALL types not defined in the specification! Thus, Winery DOES support them.

The issue should be titled: "Winery does not have native support for non-normative types used in the YAML 1.1 specification"

![spec excerpt](https://user-images.githubusercontent.com/18282351/33259972-cdd730c8-d35e-11e7-9cf9-d8a4ee3a477e.png)

**Comment by hnicke** [comment]
Maybe i forgot to tell you -- maybe you never asked me -- but for me, it was obvious that we have to supply the parser with the node type definitions of the non-normative node types.
I will create these yaml files. Including them natively in winery would be awesome!

**Comment by hnicke** [comment]
[Implemented](https://github.com/StuPro-TOSCAna/winery/commit/7590a04f4907bc2d3a954c1e2196aea40cb9432e) in our fork of winery and waiting to [go upstream](https://github.com/eclipse/winery/pull/202).
Closing this as we currently use our fork anyways.
