### ISSUE TITLE
Create organization for the project

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#28]
In the recent meeting we decided to create a organization as the owner of the repository.

This has to be done by  @nfode

**Comment by nfode** [comment]
No problem! I am interested what has lead to this decision?

**Comment by hnicke** [comment]
i think it had to do with CI, not sure though

**Comment by nfode** [comment]
Ok, so what date do we set to switch to the other repo? Everyone should realize that we switched repos.

**Comment by hnicke** [comment]
If you got time, today would be a good day :)

_Sent from my Samsung SM-G900F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nfode** [comment]
Done.
