### ISSUE TITLE
Investigate how existing solutions can benefit the CloudFormation Plugin

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/TOSCAna#290]
There are many different open-source projects dealing with AWS and AWS CloudFormation. These projects should be investigated since some of them might prove to be of use for our CloudFormation Plugin. 

A lot of them can be found here:
https://github.com/aws

A project regarding CloudFormation template creation in Java:
https://github.com/scaleset/cloudformation-builder

Jenkins Pipeline Step Plugin for AWS:
https://github.com/jenkinsci/pipeline-aws-plugin

**Comment by c-mueller** [comment]
> A project regarding CloudFormation template creation in Java:
https://github.com/scaleset/cloudformation-builder

I would not recommend using this Library. 
- First of all the repository is dead. (No contributions in the last 3 years)
- Another problem is the missing License. That means "All Rights reserved". Please only use Libraries with MIT or Apache 2 License. (Some other ones like The Unlicense also work, but no GPL, AGPL or LGPL) This is because our project is also Licensed under Apache 2

Please also consider using the Model classes provided by the java AWS SDK if they fulfill your needs (didn't investigate that):
https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-cloudformation/src/main/java/com/amazonaws/services/cloudformation/model

**Comment by mmunozba** [comment]
I'd agree, sounds like [cloudformation-builder](https://github.com/scaleset/cloudformation-builder) isn't fit for use. 
The license isn't properly set up in GitHub, but the bottom of the readme says it's under Apache 2.0.
The part about it not receiving updates for 3 years worries me aswell. It also seems that the builder only supports the creation of JSON templates since the YAML support for CloudFormation was added in 2016.
I'm not sure if @mklopp decided on whether we use JSON or YAML, but I'd prefer YAML over JSON.

Thanks, I'll definitely take a closer look at the model.

**Comment by mmunozba** [comment]
I've been taking a closer look at the amazon java sdk. Here are some notes.
- aws-sdk-java
    - 2.0 Preview version exists. Though it is not recommended to be used and from what I've looked at, there seems to be no resources there yet that we could properly use.
    - The SDK is licensed under Apache 2.0, so we should'nt have a problem there.

- aws-java-sdk-cloudformation
    - Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/Welcome.html
    - Model seems to be usable. Stacks, StackResources and Parameters etc. can be defined as Data types needed for the creation of the template. 
    - I'm going to attempt to fully model our LAMP template with this.

**Comment by mmunozba** [comment]
Upon further inspection, the model provided by the Java SDK does not seem to be sufficient for our use.
See #304.

**Comment by hnicke** [comment]
Why is cloudformation-builder not usable? @mmunozba said the license is Apache2.0.
It didn't receive an update for 3 years, but maybe it's still up to date with cloudformation manifest language?

**Comment by mmunozba** [comment]
I'll take a closer look at it again,

**Comment by mmunozba** [comment]
Here are some notes from investigation:

Shortcomings of CF-Builder:
- Obscure way of defining models with "Module" class
- Close to no documentation. This forced me to spend a considerable amount of time with trying to understand the code and the generation of models. Sadly the author only gives a single use example and trying to extrapolate how to use the builder from this simple example was quite difficult for me due to the unintuitive design of the builder.
- Almost everything done with "Object", no type-security
- Very limited number of Types, e.g. 'AWS::RDS::DBInstance' does not exist

Smaller issues/bugs
- ConstraintDescription doesn't work
- Description of Template not "settable"
- GroupDescription for SecurityGroup?

That being said, it is definitely possible to use this CF-Builder as a code base and expand upon and refactor/improve it.

I'll have to talk this over with @mklopp and we'll have to decide whether it is worth it to use CF-Builder as a base and enhance and adjust it for our plugin or whether we should just continue building our own data model.

**Comment by mmunozba** [comment]
While the results are still things to be discussed, I consider the investigation of other projects in regards to the current state of the plugin and enabling the transformation for the LAMP CSAR to be finished.
This discussion or rather the results of this discussion will be recorded in #309.

There still could be value for these projects in later stages of the plugin development, for Testing the deployed templates on the AWS platform with the Jenkins Pipeline and the AWS CloudFormation Java SDK, so I moved this to #327.
