### ISSUE TITLE
Usage of the "plugin" label

### ISSUE THREAD

**Issue by mmunozba** [StuPro-TOSCAna/TOSCAna#291]
I'm not sure which of these is the right usage.
1. The `plugin` label should be put on ALL issues regarding ANY one, two or ALL plugins.
2. The `plugin` label should be put on ONLY the issues regarding ALL plugins.

Both usages make sense to me, 1. would get you all issues regarding plugins and 2. would only give you the issues that affect all plugins.

**Comment by c-mueller** [comment]
I think this label should be used if the issue is general and all plugins are affected somehow.

BTW: I changed `lable` to `label` in the title and your text.

**Comment by nfode** [comment]
I think the same as @c-mueller. Do not know how I used it before but now we should use it like this.

**Comment by mmunozba** [comment]
Ok, then I'd say we use the 2. definition, so the `plugin` label should be used for general issues regarding ALL plugins.

I consider this issue closed then.
