### ISSUE TITLE
How to seperate Unit and Integration tests

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#297]
We are currently in a state where we get some integration tests. therefore we should investigate a solution to seperate them from regular unit tests.

Once we found a solution, i will add a ADR when realizing the chosen option

Possible Approaches:
- Use JUnit [Categories](https://github.com/junit-team/junit4/wiki/categories)
	- `+` Supported by Maven and IntelliJ (Categories to execute can be selected)
	- `+` Quite easy to use/setup
	- `-` Both test categories feature the same `source` and `resources` folder
- Use Seperated `integration` and `test` folders [See here](https://www.petrikainulainen.net/programming/maven/integration-testing-with-maven/)
	- `+` Clear differentiation between integration and unit tests
	- `-` Integration tests have to contain a specific string (e.g. the files have to end with `IT.java`)
- Put the integration tests in a seperate module
	- `+` Clear differentiation between integration and unit tests (even clearer than with a IT folder)
	- `-` Possible problems when computing the coverage from integration tests

I personally would prefer the first option (JUnit Categories). Because it is still possible to seperate the tests by putting them in different packages. (As long as there is no issue with visibilies)

**Comment by hnicke** [comment]
I prefer the second option: I think it's beneficial to have test and testee in the same package (visibility wise).
With this method, I'd also appreciate the strict division between integration and unit test classes; this could force the developer to stop and think about which kind of test he is actually currently writing.
