### ISSUE TITLE
Design a web app

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#31]
Design a web app to provide a gui for our transformator.

**Comment by mmunozba** [comment]
Here are some general requirements from the [requirements document](https://github.com/StuPro-TOSCAna/TOSCAna/blob/requirements/docs/requirements/requirements.md):

| What | How |
|-|-|
|Type|Web Application|
|Supported browsers|Firefox, Chrome|
|Communication|REST-calls|
|Technology|Angular 4|

**Ease of Use** - The UI must be simple and easy to use. The transformation should be achieved within a handful of clicks.
**Look and Feel** - The UI must look awesome. No further requirements.

**Comment by JensMueller2709** [comment]
i start to collect the requirements which belongs to the gui in a own [gui-requirement](https://github.com/StuPro-TOSCAna/TOSCAna/blob/GUI/docs/draft/gui-requirements.md)

**Comment by JensMueller2709** [comment]
how discussed in the last meeting, we move back the GUI.
