### ISSUE TITLE
Hash codes of relationships have to differ

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#337]
While messing with JGraphT to model the topology. (Seems to be a better idea, compared to messing with it manually) I was wondering why only one of the Relationships gets added and all the others fail. 

Well it comes out to be the following issue: 

When executing this code:
```java
HostedOn relA = HostedOn.builder().build();
HostedOn relB = HostedOn.builder().build();

System.out.println(relA.hashCode());
System.out.println(relB.hashCode());
```
The result comes out to be:
```
177
177

Process finished with exit code 0
```

This is kind of expected, because the contents of the objects are equal and their hashcode should be equal too.

However, to make JGraphT work properly, these values have to be different.

Currently i am using the following "workaround": Adding a unique description to the relationship while constructing the model. 
My idea to fix this was the following: Instead of the description beeing empty by default it will be `UUID.randomUUID().toString()` (maybe with some sort of prefix to remove it when getting the attribute).

**Comment by c-mueller** [comment]
Did find a decent solution that does not need the modification of the model itself.

Instead of putting the relationships in the graph directly, we use a wrapper class:
```java
@Data
public class RelationshipContainer {
    private final RootNode source;
    private final RootNode target;
    private final RootRelationship relationship;

    public RelationshipContainer(RootNode source, RootNode target, RootRelationship relationship) {
        this.source = source;
        this.target = target;
        this.relationship = relationship;
    }
}
```

This ensures that every different edge is unique and resolves this issue. 

This can be closed because of this.

**Comment by hnicke** [comment]
this is a hack. the solution is very simple: add a private uuid to the rootrelation class. youre done - lomboks data annotations will automagically update the equals and hash method.

**Comment by hnicke** [comment]
Having such a wrapper class seems brittle: Information about connections between nodes and relationships are stored twice. This is an unnecessary risk.

**Comment by c-mueller** [comment]
I just want to add that the `DefaultEdge` class from jgrapht also contains the source and the edge. 

Storing the Source and target in the relationship would also make it way easier to iterate over the graph. which is kind of a pain currently!
