### ISSUE TITLE
Rename component 'archive'

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#34]
In our current drafts, we use the word 'archive' for naming our storage component.
This seems wrong to me:
- we don't archive data. we rather store data for current usage, and probably drop it again afterwards
- it's a naming conflict with the term 'csar' (cloud service archive) : we would store archives in the archive. what the heck

Some alternatives:
- store
- stock
- storage
- dataaccess (DA)

Feel free to post your suggestions.

**Comment by c-mueller** [comment]
`storage` looks like a good name for me.

**Comment by hnicke** [comment]
chris and me agreed upon the package name 'persist'
