### ISSUE TITLE
Investigate how DB Credentials can be retrieved 

### ISSUE THREAD

**Issue by orferch** [StuPro-TOSCAna/TOSCAna#352]
Find a way to retrieve the Credentials provided from Cloudfoundry of a running Database Service. If possible, find a way to set them before launching the Service.

**Comment by orferch** [comment]
While investigating this task, the following results were found:

-  Setting of credentials for provided Marketplace MySQL not possible
- linking of user provided Service doesn't work with provided marketplace service
- Query of credentials from the provided service is possible in 2 Ways:

Parse the JSON yourself: See the documentation for VCAP_SERVICES. Helper libraries are available for some frameworks.

Not really solving the issue, because it would need to deploy while transforming the CSAR.

Auto-configuration: Some buildpacks create a service connection for you by creating additional environment variables, updating config files, or passing system parameters to the JVM.

Auto-configuration would be possible with writing 
```
$service_blob = json_decode($_ENV['VCAP_SERVICES'], true);
$db_name = $service_blob['cleardb'][0]['credentials']['name'];
$db_host = $service_blob['cleardb'][0]['credentials']['hostname'];
$db_user = $service_blob['cleardb'][0]['credentials']['username'];
$db_password = $service_blob['cleardb'][0]['credentials']['password'];
$db_port = $service_blob['cleardb'][0]['credentials']['port'];
```
into a php file, but db_name etc. would have to be always the same for any CSAR which uses a MySQL DB. Adding this to Tosca Spec is possible.

That means the current best way would be to call the `VCAP_SERVICES` with `cf env APPNAME` and write it manually into the `manifest.yml`.

**Comment by JensMueller2709** [comment]
PR #385 tries to give a solution.

**Comment by JensMueller2709** [comment]
already implemented
