### ISSUE TITLE
Implement TOSCA input feature in model converter

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#374]
The `TServiceTemplate-to-EffectiveModel-converter` shall support the concept of TOSCA inputs.

- [x] collect declared inputs from `TServiceTemplate`
- [x] request declared inputs as user input
  - [x] test and debug `server`
  - [x] test and debug `cli` component (for sure doesn't work yet)
- [x] dynamically link properties #380

**Comment by c-mueller** [comment]
is this still a thing? Or has this been implemented?

**Comment by hnicke** [comment]
Got implemented long ago.
