### ISSUE TITLE
Provide SQL file to MySQL Service to create tables

### ISSUE THREAD

**Issue by orferch** [StuPro-TOSCAna/TOSCAna#375]
Investigate how to provide SQL files to the Service, to create the wanted tables after the Service is started.

**Comment by JensMueller2709** [comment]
This with this [project](https://github.com/andreasf/cf-mysql-plugin) we could connect to a mysql database and could execute a sql-File. How we already discussed, we try to use it.

**Comment by orferch** [comment]
Currently working Solution:

on Server:
- App is connected to the MySQL Service

on Local Machine:
- cloud-foundry cli is installed
- install cf-mysql-plugin with `cf install-plugin -r "CF-Community" mysql-plugin`
- install mysql-server

move into the folder with the *.sql file and connect to the created MySQL Service:
- show available Services: `cf mysql`
- connect to the Database: `cf mysql mydbname`
- provide the .sql file with `source filename.sql`

MySQL runs now with the provided Information of the .sql


We will look more into running Scripts to automate this whole process.
