### ISSUE TITLE
How to handle internal dependencies

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#40]
While designing the data model, a question arises:
How do we handle internal dependencies? Possiblities are:
- **Constructor Injection**: If Class A needs Class B, Class A receives the reference to an instance of Class B in its constructor. If dependencies are cyclic, also use setters.
  - *pro*: less magic happens, more transparency
   - *con*: tedious to administrate, constructors often change when project grows
- **Dependency Injection (DI) via Spring**: read [here](http://www.vogella.com/tutorials/SpringDependencyInjection/article.html).
  - *pro*: automates the rather tedious tasks of distributing references
  - *con*: (I've never taken this route, so i only guess) read [this rant](https://dzone.com/articles/dependency-injection-makes), maybe also the comments. Summary: Dependencies are harmful and should be reduced, and having a framework for lessening the burden of dependency management therefore could be destructive.

I'd like to go the Spring DI route this time. What do you think?

**Comment by JensMueller2709** [comment]
it seems to be a nice concept to handle class dependencies. But in my opinion it is a new concept for the most of us and therefore it think we should use the "normal" way in the first version to save the training period.

**Comment by hnicke** [comment]
As I'm now a member of the core team, I'm currently learning the spring framework. I now decide that we use Springs Dependency Injection.
