### ISSUE TITLE
Adapt the lamp model to be a twelve factor app

### ISSUE THREAD

**Issue by JensMueller2709** [StuPro-TOSCAna/TOSCAna#409]
While our meeting today it was mentioned that the plugins could assume only applications/models which are designed by the [12 factor logic](https://12factor.net/).

**Comment by JensMueller2709** [comment]
Therefore we should adapt the common Lamp-Model or create a new one until end of Sprint 8.

**Comment by c-mueller** [comment]
As i have already mentioned. The SimpleTaskApp can be considered Twelve factor compatible in many ponts. However some just cannot get supported without rethinking the whole application.
