### ISSUE TITLE
Implement common deploy() phase

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#439]
The goal is to call the `deploy.sh` file created by every plugin.

**Comment by hnicke** [comment]
I'd like to tackle this next.

However, I am not sure whether this should get implemented as a lifecycle phase, or rather as a seperate call.
What are the pros and cons?

**Comment by c-mueller** [comment]
Since we do not implement Deployment from within the Transformer anymore. This issue will be closed!
