### ISSUE TITLE
Provide transformation phase to the rest api

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#455]
Currently is is only possible to get the current transformation status not the transformation phase.

I would deliver the result with the **GET** `csars/csarId/transformations/platform` call.

Example (Stripped the links for readability):
```
{
  "progress": 0,
  "status": "READY",
  "platform": "cloud-foundry",
  "phases": [
    {
      "id": 0,
      "name": "validate",
      "status": "DONE"
    },
    {
      "id": 1,
      "name": "prepare",
      "status": "WAITING"
    }
  ]
}
```
As Phase status I would suggest: WAITING, RUNNING, DONE, ERROR.

Another possibility is to create a own call for the transformation phases like: `csars/csarId/transformations/platform/phases`.

**Comment by hnicke** [comment]
Thank you for the proposal. I like it. I'd add a 'SKIPPED' status.
Why is the phase name lowercase, but the phase status uppercase? This appears inconsistent to me.
@c-mueller what do you think? I'd implement this feature this afternoon (at least necessary non-api changes).

**Comment by hnicke** [comment]
I am currently implementing the backend part of this feature. Currently, an execution phase doesn't have an ID. Why does a phase need an ID? The phases array will already be delivered in the right order.
