### ISSUE TITLE
CloudFormation logging

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#495]
Currently CloudFormation has a quite bloated log. I think one log line stating it is compressing transformation artifacts might be enough.

![](https://i.imgur.com/VDTR7Vq.png)

**Comment by mmunozba** [comment]
This log entry happens here:
https://github.com/StuPro-TOSCAna/TOSCAna/blob/9ece25b11ac3466ec139496628a376dbdf5a8e19/server/src/main/java/org/opentosca/toscana/core/transformation/execution/ExecutionTask.java#L62

Not 100% sure what happens here, so I don't know how the CloudFormation Plugin is causing so many log entries. Could @hnicke or @c-mueller explain what's happening here?

**Comment by hnicke** [comment]
Please supply the server logs.

**Comment by hnicke** [comment]
Can not reproduce the bug. Please provide additional steps for reproduction and/or the server log.

**Comment by hnicke** [comment]
Most probably solved as soon as changes from aed2177f68b1e7d203f286f6e03b9d78d87d66e0 make it to the master.
