### ISSUE TITLE
Expose swagger ui at stupro-toscana.de

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#506]
We need to expose the swagger ui at stupro-toscana for:
1. demonstration of our api
2. quick debugging of web app behaviour

**Comment by c-mueller** [comment]
Is this really that important? we could always refer to https://app.stupro-toscana.de/swagger-ui.html

**Comment by hnicke** [comment]
Somehow I thought this mapping wouldn't work. Thanks for clarifying.
