### ISSUE TITLE
Getting environment variables during runtime

### ISSUE THREAD

**Issue by JensMueller2709** [StuPro-TOSCAna/TOSCAna#517]
To avoid replacing values in some files e.g. in the Lamp-App (`sed -i ....`) the cloud formation plugin should check if it is possible to set environment variables for php during runtime. So the php application could use `getEnv...`. 
We already discussed this topic several times in our meetings. 

Why I created this Issue? The current workaround causes some problems in the CloudFoundry plugin.

**Comment by mmunozba** [comment]
As discussed, this is possible. I'll be addressing the implementation for AWS in #572.
