### ISSUE TITLE
Key Attribute of OperationVariable not set properly

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#526]
While Attempting to implement the support for the Java Model. I encountered the following issue: The Environment variable names are not set properly. The Transformation currently produces the following Dockerfile for the Apache Node of the Java-Translator odel:
```Dockerfile
FROM library/php:apache
ENV value=3306
ENV value=stadb
ENV value=TOSCA_rulez
ENV value=stadb
ENV database_host=my-db-service
WORKDIR /toscana-root
COPY my_app/mysql-credentials.php mysql-credentials.php
COPY my_app/myphpapp.php myphpapp.php
COPY my_app/my_app-create my_app-create
COPY my_app/my_app-configure my_app-configure
RUN apt-get update && apt-get install -y sudo; true
RUN sh my_app-create
RUN sh my_app-configure
RUN docker-php-ext-install mysqli
```
But the env variables should have the associated key set properly(i.e. value has to be database_port, database_password...)

The Code Producing this can be found in:
`DockerfileBuildingVisitor -> copyAndExecIfPresent -> ~Line 258` ( in the `feature/k8s/support-java-types` branch)

This only seems to happen with this specific model and node. The resuslts produced otherwise did not contain such problematic names. (Did only look at the dockerfiles not at the produced result)

**Comment by hnicke** [comment]
Note to myself: When transforming 'lamp-input.csar' to CloudFoundry, and inserting `123` for all required inputs, the log says:
```
Application | DEBUG | Add environment variable value with value 123 to manifest
Application | DEBUG | Add environment variable value with value 123 to manifest
Application | DEBUG | Add environment variable value with value 123 to manifest
Application | DEBUG | Add environment variable value with value 123 to manifest
```
