### ISSUE TITLE
Add ability to change POSIX File permissions using the PluginFileAccess

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#545]
To allow the execution of a Shell script (i.e. `deploy.sh`) we should make them executable by default during the creation. This can be achieved by adding a option to change the file access permissions using the PluginFileAccess. 

We could also consider to just add a function `makeExecutable(String scriptPath)`

**Comment by hnicke** [comment]
@c-mueller Is this still needed?
