### ISSUE TITLE
Create a contribution guide

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#6]
Create a contribution guide which explains:
- usage of zenhub issue board (incl. pipes, labels)
- git commit and pull request strategy

**Comment by nfode** [comment]
To identify subtasks I tried to split your points in more detailed ones:
- usage of zenhub issue board (incl. pipes, labels):
   - What does every pipeline mean? When should it be used?
   - What labels do we have and when is it ok to use them?
- git commit and pull request strategy
   - a link to the branching model we use and maybe a short description with a image
   - [wip] (work in progess) label for Pull Request
   - best practices on merging, squashing or rebasing PRs -> When should I choose [insert variant] to merge my PR?

I also had some more ideas:
- bug report
   -  Things a bug report should contain:
             - When does the bug appear? 
             - What steps to reproduce the bug? 
             - The log file. 
             -  a screenshot for UI 
     I think a standard for bug reports might be useful for someone to test the bug in his environment or to solve the bug. 
- releases
  - a short guide to the usage of [SemVer](http://semver.org/] if we use it
