### ISSUE TITLE
Csar status

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#64]
We might need to add some sort of status to the csar objects.
Reason:
- If parsing fails, no in-memory template can be offered to the plugins

What needs to change:
- add state to csar with getters/setters {valid,invalid} at least
- add means to query csar state with rest api

**Comment by c-mueller** [comment]
Well this actually brings another question to my mind. Do we want to allow the user to access the logging output of the csar parser? if it actually has any

**Comment by hnicke** [comment]
would be nice. this would mean we add a logfile to the csar directly (same as with transformations)

another idea i just had: CsarService.submitCsar() returns new Csar on success. It could simply return null if parsing fails. In other words, the system will not allow submission of invalid csars in the first place. This approach is simpler but makes it harder to propagate parsing logs to end user. Though logs could be, csar-independently, stored in some kind of general system log accessible via REST api..

**Comment by c-mueller** [comment]
The status approach has been replaced by a error handling mechanism that returns a special error message also containing the logs if the parsing of the csar fails. if it was sucessfull the logs can be receieved with a `/csars/{name}/logs` call (just like the transformation version)

**Comment by hnicke** [comment]
implemented
