### ISSUE TITLE
Enforce spaces over tabs

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#67]
When looking at commit 37d696c it can be seen that the changelog is intransparent due to different IDE settings regarding spaces and tabs.
I suggest to enforce the usage of spaces over tabs.

How can this be achieved in a foolproof, project-wide manner?

**Comment by hnicke** [comment]
done with f8152fa, thx

**Comment by c-mueller** [comment]
Also fixed in the master branch with the commit 2e3866b4718d2cc049ddb274c0f097eb39e43fa1 please update your branches too @nfode @mklopp @orferch @bnguyen3 @mmunozba @JensMueller2709
