### ISSUE TITLE
Define a plugin interface

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#69]
In order to allow the plugins to be handled in a abstract way we need a interface for them to allow the core to access them. For loading the dependencies Spring Boots Annotation based Dependency injection will be used.

**Comment by hnicke** [comment]
It got implemented but is lacking documentation.

**Comment by c-mueller** [comment]
Currently working on that!

**Comment by c-mueller** [comment]
Did create some docs a but the transformation context and the plugin file access still need some more documentation
