### ISSUE TITLE
IntelliJ Editor config

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#76]
Additional to the checkstyle config we could add a IntelliJ editor config to automatically enforce the checkstyle.

I added a config file in the master branch ([link](https://github.com/StuPro-TOSCAna/TOSCAna/blob/master/docs/ide_config/IntelliJ_Codestyle.xml)).

Here a guide how to enable it: [link](https://github.com/eclipse/winery/tree/master/docs/dev/config/IntelliJ%20IDEA) (Nr. 4).

I consider this as useful. If anything speaks against this please comment, else add this to your editor.

**Comment by hnicke** [comment]
Additionally, the `save action` [plugin](https://plugins.jetbrains.com/plugin/7642-save-actions) might be useful. With this plugin,  you can enable `code reformat` and `optimize imports` on save if you want.

**Comment by nfode** [comment]
Since no one despite @hnicke commented, please add the config.  
@hnicke s plugin is useful but if you ensure that everything is well formed without the plugin you do not need to install it.

**Comment by hnicke** [comment]
I highly encourage you all to use the `save action` plugin. 
It's not about nice code formatting -- its all about same code formatting - with every commit. This will help to keep the amount of changed files low.

**Comment by orferch** [comment]
done

**Comment by nfode** [comment]
Fixed error in the `checkstyle.xml` it might be possible that you have to reimport it.

**Comment by hnicke** [comment]
@nfode @orferch @c-mueller @JensMueller2709 @mklopp @mmunozba @bnguyen3 Important: I've fixed the codestyle (docs/ide_config/IntelliJ_Codestyle.xml). Please reimport the code style (paragraph 4: [link](https://github.com/eclipse/winery/tree/master/docs/dev/config/IntelliJ%20IDEA))

With this change, JavaDoc will be much easier to write.
