### ISSUE TITLE
TransformationDao must set TransformationState accordingly

### ISSUE THREAD

**Issue by hnicke** [StuPro-TOSCAna/TOSCAna#77]
When reading transformations from disk, new Transformation instances are created. Afterwards they have the default transformation state "created".
Add logic to TransformationDao which detects in which state the transformation really is.

**Comment by c-mueller** [comment]
Well i just found out that this problem does not only affect the state. A launched transfomation also does not have any logs in the Log object even tough it did produce logs!

**Comment by hnicke** [comment]
log persistency is not yet implemented

**Comment by hnicke** [comment]
Log persistency is implemented, so this issue can get solved.
