### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#81]
I was just taking a look and i saw that the Into on our readme is wrong

> The TOSCAna framework allows the transformation of TOSCA models into other cloud formats. Currently, it aims to support multiple cloud ecosystems, with Amazon Web Services and their AWS Cloud Formation being the first.

Maybe someone can change this?

**Comment by nfode** [comment]
I am to lazy to detect you want to change? Please add what you mean. 
Do you mean that Kubernetes and CloudFoundry are missing?
