### ISSUE TITLE
Create issues for tasks you work on

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#88]
We have a lack of communication so I recommend to create a issue for every task you detect working on your problem like @hnicke and @c-mueller did working on the core. 

If everyone creates issues everyone can read them and sees if there are tasks they also have to tackle.

Also if they are updated and moved between the pipes on the board it eases to see the current progress.

I'd like to hear your opinion.

**Comment by c-mueller** [comment]
Well we have ZenHub for a reason. Not using it seems idiotic. 

Adding estimates (just how you would measure the issue) and the corresponding sprint milestone would also be nice.

Linking issues withe epics is also a nice feature and is not completely useless :)
