### ISSUE TITLE
Faster pull request merging

### ISSUE THREAD

**Issue by nfode** [StuPro-TOSCAna/TOSCAna#89]
Like in the preliminary studies we have huge pull requests that are hard to review.

Since the core now is in master we have the possibility to create pull requests faster with a small amount of changes. 

**Now is the question how do we recognize a stable version?**
We discussed to use a dev branch to merge everything there and only a stable version goes into master.
In the last sprint we skipped the dev branch and just merge into master. It seems like this fits better.
So I would say we skip dev, merge into master and tag stable versions (  @c-mueller recommented this at the beginning).

I'd like to hear you opinion or recommendations.

**Comment by hnicke** [comment]
I'd like to postpone this decission.
The soonest point for the dev branch to be useful is when we reach our first stable version/tag (0.1).

**Comment by nfode** [comment]
@hnicke We can postpone this but i think it is still important to merge faster. I dont want to spent another hour fixing things because of the big changes to the master!

**Comment by hnicke** [comment]
This issue is not solved with a dev branch / without one. 
If you want your changes to get merged sooner, remove the [WIP] tag and invite your fellow developers to review your code.

**Comment by nfode** [comment]
Ok my issues is a bit missleading. My changes cannot  be merged faster if I am depending on another work in progress like the core...

**Comment by hnicke** [comment]
I see your problem, and this was the reason @c-mueller and me decided to merge the core into master. Hopefully this situation will not happen again.

**Comment by nfode** [comment]
Yeah the goal of this issue was to reach awareness for this Problem. Maybe I failed and typed to quick -.-
