### ISSUE TITLE
Correctly setup codacy

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#91]
Some Codacy "warnings" are just stupid, because they dont really improve code qualtiy in any way. Some are just incrorrect.

Just some examples:
![image](https://user-images.githubusercontent.com/2706976/32058022-3069c44e-ba69-11e7-889f-2b888cb4e2e8.png)
![image](https://user-images.githubusercontent.com/2706976/32058084-64f74a88-ba69-11e7-814c-ffe9d5acd339.png)

The first one might be discussable, but it does not affect anything and im pretty sure nobody reads the imports or gets annoyed by them beeing in the wrong order.

The second one is just stupid because these tests all have a failing condition it is just not containd in the direct method body of the test method, it might be caused by a seperate framework (`andExpect()` from spring) or the assertion just not beeing within the body of the method (its in a subroutine)

The rest of the issue does not seem to be an issue but just removing these 2 issues will get rid of about 110 complaints.

**Comment by nfode** [comment]
Disabled Nr. 2 because I don't think it makes any sense if somebody thinks it should be re enabled raise your hand.

**Comment by c-mueller** [comment]
Problem should be fixed, gonna reopen this issue if it hasn't been fixed by the recent Intellij Setting and the deactivation of the test warning
